### ISSUE TITLE
SnapChat errors on IOS

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [TimmyRB/snapkit#4]
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(SendMediaSendError, Optional(Error Domain=SCSDKCreativeKitErrorDomain Code=4 "error_description_encryption_metadata_read_failure" UserInfo={NSLocalizedRecoverySuggestion=Please contact snapkit-support@snap.com if problem persists., NSLocalizedDescription=error_description_encryption_metadata_read_failure, NSLocalizedFailureReason=}), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      Snapkit.share (package:snapkit/snapkit.dart:129:5)
<asynchronous suspension>

**Comment by TimmyRB** [comment]
This error usually occurs because you have not set your Platform Identifiers on the Snapchat Developer Portal correctly.

Please make sure to add them by going to the Developer Portal, click on your application, click on your desired version then scroll down to Platform Identifiers and input values similar to these except with your own Bundle ID and Android App ID
<img width="980" alt="image" src="https://user-images.githubusercontent.com/19505665/126042098-6b6f1a2c-54fa-4f43-a60d-2f30ab3c2768.png">

**Comment by officialFlutterDeveloper** [comment]
thank you for the response but I did that before already but it didn't worked
<img width="1204" alt="Screenshot 2021-07-18 at 13 32 44" src="https://user-images.githubusercontent.com/82877513/126061048-4af8bdd5-793f-4a19-a076-53350d7c8122.png">

**Comment by TimmyRB** [comment]
Make sure you also have a demo Snapchat user set and you followed these [instructions](https://github.com/TimmyRB/snapkit/wiki/iOS-Installation#infoplist) to set your iOS Info.plist correctly
<img width="979" alt="image" src="https://user-images.githubusercontent.com/19505665/126073877-6a6d6541-21cd-4e49-8d8d-c11b74758698.png">
This section can be found above Platform Identifiers
